/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mnsc_service_CONSTANTS_H
#define mnsc_service_CONSTANTS_H

#include "mnsc_service_types.h"

namespace meituan_mns {

class mnsc_serviceConstants {
 public:
  mnsc_serviceConstants();

};

extern const mnsc_serviceConstants g_mnsc_service_constants;

} // namespace

#endif
