/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mnsc_data_CONSTANTS_H
#define mnsc_data_CONSTANTS_H

#include "mnsc_data_types.h"

namespace meituan_mns {

class mnsc_dataConstants {
 public:
  mnsc_dataConstants();

  std::string PROD;
  std::string STAGE;
  std::string TEST;
  int32_t SUCCESS;
  int32_t MNSCache_UPDATE;
  int32_t TIMEOUT_ERROR;
  int32_t ILLEGAL_ARGUMENT;
  int32_t NOT_FOUND;
  int32_t NOT_MODIFIED;
};

extern const mnsc_dataConstants g_mnsc_data_constants;

} // namespace

#endif
