/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef naming_common_CONSTANTS_H
#define naming_common_CONSTANTS_H

#include "naming_common_types.h"

namespace meituan_mns {

class naming_commonConstants {
 public:
  naming_commonConstants();

};

extern const naming_commonConstants g_naming_common_constants;

} // namespace

#endif
