/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef naming_data_CONSTANTS_H
#define naming_data_CONSTANTS_H

#include "naming_data_types.h"

namespace meituan_mns {

class naming_dataConstants {
 public:
  naming_dataConstants();

};

extern const naming_dataConstants g_naming_data_constants;

} // namespace

#endif
