/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef naming_service_CONSTANTS_H
#define naming_service_CONSTANTS_H

#include "naming_service_types.h"

namespace meituan_mns {

class naming_serviceConstants {
 public:
  naming_serviceConstants();

};

extern const naming_serviceConstants g_naming_service_constants;

} // namespace

#endif
