/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftSpans_CONSTANTS_H
#define ThriftSpans_CONSTANTS_H

#include "ThriftSpans_types.h"



class ThriftSpansConstants {
 public:
  ThriftSpansConstants();

};

extern const ThriftSpansConstants g_ThriftSpans_constants;



#endif
