/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef unified_protocol_CONSTANTS_H
#define unified_protocol_CONSTANTS_H

#include "unified_protocol_types.h"

namespace meituan_mns {

class unified_protocolConstants {
 public:
  unified_protocolConstants();

};

extern const unified_protocolConstants g_unified_protocol_constants;

} // namespace

#endif
