/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef echo_CONSTANTS_H
#define echo_CONSTANTS_H

#include "echo_types.h"

namespace echo {

class echoConstants {
 public:
  echoConstants();

};

extern const echoConstants g_echo_constants;

} // namespace

#endif
